AppAspGroupe1/Models/Gestionnaire.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace AppAspGroupe1.Models
{
    public class Gestionnaire:Utilisateur

    {
        

        [Display(Name = "CNI"), Required(ErrorMessage = "*"), MaxLength(20)]
        public string CNIGestionnaire { get; set; }

        public virtual ICollection <Agence> Agences { get; set; }



    }
}

AppAspGroupe1/Controllers/GestionnairesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppAspGroupe1.Models;
using PagedList;

namespace AppAspGroupe1.Controllers
{
    public class GestionnairesController : Controller
    {
        private BdAgenceVoyageContext db = new BdAgenceVoyageContext();
        private const int pageSize = 2; // Nombre d'éléments par page

        // GET: Gestionnaires
        public ActionResult Index(string nom, string prenom, int? page)
        {
            ViewBag.Nom = nom!=null?  nom: string.Empty;
            ViewBag.Prenom = prenom!=null?  prenom: string.Empty;
            
            var listes = db.gestionnaires.ToList();
            

            if (!string.IsNullOrEmpty(nom))
            {
                listes = (List<Gestionnaire>)listes.Where(g => g.NomUtilisateur.ToLower().Contains(nom.ToLower()));
            }
            if (!string.IsNullOrEmpty(prenom))
            {
                listes = (List<Gestionnaire>)listes.Where(g => g.PrenomUtilisateur.ToLower().Contains(prenom.ToLower()));
            }


            page = page.HasValue ? page : 1;
            int pageNumber = (int)page;
            return View(listes.OrderBy(g => g.NomUtilisateur).ToPagedList(pageNumber, pageSize));
        }

        // GET: Gestionnaires/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Gestionnaire gestionnaire = db.utilisateurs.Find(id) as Gestionnaire;

            if (gestionnaire == null)
                return HttpNotFound();

            return View(gestionnaire);
        }

        // GET: Gestionnaires/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gestionnaires/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUtilisateur,NomUtilisateur,PrenomUtilisateur,EmailUtilisateur,TelUtilisateur,CNIGestionnaire")] Gestionnaire gestionnaire)
        {
            if (ModelState.IsValid)
            {
                db.utilisateurs.Add(gestionnaire);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gestionnaire);
        }

        // GET: Gestionnaires/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Gestionnaire gestionnaire = db.utilisateurs.Find(id) as Gestionnaire;

            if (gestionnaire == null)
                return HttpNotFound();

            return View(gestionnaire);
        }

        // POST: Gestionnaires/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUtilisateur,NomUtilisateur,PrenomUtilisateur,EmailUtilisateur,TelUtilisateur,CNIGestionnaire")] Gestionnaire gestionnaire)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gestionnaire).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gestionnaire);
        }

        // GET: Gestionnaires/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Gestionnaire gestionnaire = db.utilisateurs.Find(id) as Gestionnaire;

            if (gestionnaire == null)
                return HttpNotFound();

            return View(gestionnaire);
        }

        // POST: Gestionnaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gestionnaire gestionnaire = db.utilisateurs.Find(id) as Gestionnaire;
            if (gestionnaire != null)
            {
                db.utilisateurs.Remove(gestionnaire);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();

            base.Dispose(disposing);
        }
    }
}

AppAspGroupe1/Views/Gestionnaires/Create.cshtml
@model AppAspGroupe1.Models.Gestionnaire

@{
    ViewBag.Title = "Créer un Gestionnaire";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Créer un Gestionnaire</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Informations du Gestionnaire</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!-- Nom -->
        <div class="form-group">
            @Html.LabelFor(model => model.NomUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomUtilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Prénom -->
        <div class="form-group">
            @Html.LabelFor(model => model.PrenomUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrenomUtilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrenomUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Email -->
        <div class="form-group">
            @Html.LabelFor(model => model.EmailUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailUtilisateur, new { htmlAttributes = new { @class = "form-control", type = "email" } })
                @Html.ValidationMessageFor(model => model.EmailUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Téléphone -->
        <div class="form-group">
            @Html.LabelFor(model => model.TelUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelUtilisateur, new { htmlAttributes = new { @class = "form-control", type = "tel" } })
                @Html.ValidationMessageFor(model => model.TelUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- CNI -->
        <div class="form-group">
            @Html.LabelFor(model => model.CNIGestionnaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNIGestionnaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CNIGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

 
        <!-- Bouton de validation -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-primary" />
                @Html.ActionLink("Annuler", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

<!-- Lien retour -->
<div>
    @Html.ActionLink("Retour à la liste", "Index", null, new { @class = "btn btn-link" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppAspGroupe1/Views/Gestionnaires/Delete.cshtml
@model AppAspGroupe1.Models.Gestionnaire

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gestionnaire</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrenomUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrenomUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CNIGestionnaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNIGestionnaire)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppAspGroupe1/Views/Gestionnaires/Details.cshtml
@model AppAspGroupe1.Models.Gestionnaire

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Gestionnaire</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrenomUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrenomUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CNIGestionnaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNIGestionnaire)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdUtilisateur }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AppAspGroupe1/Views/Gestionnaires/Edit.cshtml
@model AppAspGroupe1.Models.Gestionnaire

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gestionnaire</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdUtilisateur)

        <div class="form-group">
            @Html.LabelFor(model => model.NomUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomUtilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrenomUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrenomUtilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrenomUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailUtilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelUtilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelUtilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNIGestionnaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNIGestionnaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CNIGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppAspGroupe1/Views/Gestionnaires/Index.cshtml
@model PagedList.IPagedList<AppAspGroupe1.Models.Gestionnaire>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm(("Index", "Gestionnaires", FormMethod.Get)))
{
    <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 30px;">
        <div class="form-group" style="margin-bottom: 15px;">
            @Html.Label("NomUtilisateur", htmlAttributes: new { @class = "control-label col-md-4", style = "color: #2196F3; font-weight: bold;" })
            <div class="col-md-10">
                @Html.TextBox("NomUtilisateur", ViewBag.NomUtilisateur as string, new { @class = "form-control", style = "border: 1px solid #ddd; border-radius: 4px; padding: 8px; width: 100%;" })
            </div>
        </div>

        <div class="form-group" style="margin-bottom: 15px;">
            @Html.Label("PrenomUtilisateur", htmlAttributes: new { @class = "control-label col-md-4", style = "color: #2196F3; font-weight: bold;" })
            <div class="col-md-10">
                @Html.TextBox("PrenomUtilisateur", ViewBag.PrenomUtilisateur as string, new { @class = "form-control", style = "border: 1px solid #ddd; border-radius: 4px; padding: 8px; width: 100%;" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Rechercher" class="btn btn-primary" style="background-color: #2196F3; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; transition: background-color 0.3s;" onmouseover="this.style.backgroundColor='#1e88e5'" onmouseout="this.style.backgroundColor='#2196F3'" />
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().NomUtilisateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PrenomUtilisateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().EmailUtilisateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TelUtilisateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().CNIGestionnaire)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomUtilisateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrenomUtilisateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailUtilisateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelUtilisateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CNIGestionnaire)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdUtilisateur }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdUtilisateur }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdUtilisateur })
            </td>
        </tr>
    }

</table>