AppAspGroupe1/Models/Agence.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppAspGroupe1.Models
{
    public class Agence
    {
        [Key]
        public int IdAgence { get; set; }

        [Display(Name = "AddresseAgence"), Required(ErrorMessage = "*"), MaxLength(150)]
        public string AddresseAgence { get; set; }

        [Display(Name = "Lattitude")]
        public float? Lattitude { get; set; }

        [Display(Name = "Longitude")]
        public float Longitude { get; set; }

        [Display(Name = "Ninea"), Required(ErrorMessage = "*"), MaxLength(20)]
        public string NineaGestionnaire { get; set; }

        [Display(Name = "Rcm"), Required(ErrorMessage = "*"), MaxLength(20)]
        public string RcmGestionnaire { get; set; }

        //pour avoir tous les offres de l'agence direct sans faire de requetes
        public virtual ICollection<Offre> Offres { get; set; }
        public int? IdGestionnaire { get; set; } 
        [ForeignKey("IdGestionnaire")]
        public virtual Gestionnaire Gestionnaire { get; set; }


       



    }
}

AppAspGroupe1/Controllers/AgencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppAspGroupe1.Models;
using PagedList;

namespace AppAspGroupe1.Controllers
{
    public class AgencesController : Controller
    {
        private BdAgenceVoyageContext db = new BdAgenceVoyageContext();
        const int pageSize = 1;

        // GET: Agences
        public ActionResult Index(string Adresse, string ninea, string rccn, int? page)
        {
            ViewBag.Adresse = Adresse != null ? Adresse : string.Empty;
            ViewBag.ninea = ninea != null ? ninea : string.Empty;
            ViewBag.rccn = rccn != null ? rccn : string.Empty;
            //EAGER LOADING EN RECUPERENAT AGENCE ET SES GESTIONNAIRES 
            var agences = db.Agences.Include(a => a.Gestionnaire);
            var liste = db.Agences.ToList();
            if (!string.IsNullOrEmpty(Adresse))
            {
                liste = liste.Where(a => a.AddresseAgence.ToLower().Contains(Adresse.ToLower())).ToList();
            }
            if (!string.IsNullOrEmpty(ninea))
            {
                liste = liste.Where(a => a.NineaGestionnaire.ToLower().Contains(ninea.ToLower())).ToList();
            }
            if (!string.IsNullOrEmpty(rccn))
            {
                liste = liste.Where(a => a.RcmGestionnaire.ToLower().Contains(rccn.ToLower())).ToList();
            }
            page = page.HasValue ? page : 1;
            int pageNumber = (int)page;

            return View(liste.ToPagedList(pageNumber, pageSize));
        }

        // GET: Agences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agence agence = db.Agences.Find(id);
            if (agence == null)
            {
                return HttpNotFound();
            }
            return View(agence);
        }

        // GET: Agences/Create
        public ActionResult Create()
        {
            ViewBag.IdGestionnaire = new SelectList(db.utilisateurs, "IdUtilisateur", "NomUtilisateur");
            return View();
        }

        // POST: Agences/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdAgence,AddresseAgence,Lattitude,Longitude,NineaGestionnaire,RcmGestionnaire,IdGestionnaire")] Agence agence)
        {
            if (ModelState.IsValid)
            {
                db.Agences.Add(agence);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdGestionnaire = new SelectList(db.utilisateurs, "IdUtilisateur", "NomUtilisateur", agence.IdGestionnaire);
            return View(agence);
        }

        // GET: Agences/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agence agence = db.Agences.Find(id);
            if (agence == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdGestionnaire = new SelectList(db.utilisateurs, "IdUtilisateur", "NomUtilisateur", agence.IdGestionnaire);
            return View(agence);
        }

        // POST: Agences/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAgence,AddresseAgence,Lattitude,Longitude,NineaGestionnaire,RcmGestionnaire,IdGestionnaire")] Agence agence)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agence).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdGestionnaire = new SelectList(db.utilisateurs, "IdUtilisateur", "NomUtilisateur", agence.IdGestionnaire);
            return View(agence);
        }

        // GET: Agences/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agence agence = db.Agences.Find(id);
            if (agence == null)
            {
                return HttpNotFound();
            }
            return View(agence);
        }

        // POST: Agences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agence agence = db.Agences.Find(id);
            db.Agences.Remove(agence);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppAspGroupe1/Views/Agences/Create.cshtml
@model AppAspGroupe1.Models.Agence

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AddresseAgence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddresseAgence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddresseAgence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lattitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lattitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lattitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NineaGestionnaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NineaGestionnaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NineaGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RcmGestionnaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RcmGestionnaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RcmGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdGestionnaire, "IdGestionnaire", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdGestionnaire", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppAspGroupe1/Views/Agences/Delete.cshtml
@model AppAspGroupe1.Models.Agence

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gestionnaire.NomUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gestionnaire.NomUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddresseAgence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddresseAgence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lattitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lattitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NineaGestionnaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NineaGestionnaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RcmGestionnaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RcmGestionnaire)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppAspGroupe1/Views/Agences/Details.cshtml
@model AppAspGroupe1.Models.Agence

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Agence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gestionnaire.NomUtilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gestionnaire.NomUtilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddresseAgence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddresseAgence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lattitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lattitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NineaGestionnaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NineaGestionnaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RcmGestionnaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RcmGestionnaire)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdAgence }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AppAspGroupe1/Views/Agences/Edit.cshtml
@model AppAspGroupe1.Models.Agence

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdAgence)

        <div class="form-group">
            @Html.LabelFor(model => model.AddresseAgence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddresseAgence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddresseAgence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lattitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lattitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lattitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NineaGestionnaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NineaGestionnaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NineaGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RcmGestionnaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RcmGestionnaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RcmGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdGestionnaire, "IdGestionnaire", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdGestionnaire", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdGestionnaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppAspGroupe1/Views/Agences/Index.cshtml
@model PagedList.IPagedList<AppAspGroupe1.Models.Agence>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm(("Index", "Agences", FormMethod.Get)))
{
    <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 30px;">
        <div class="form-group" style="margin-bottom: 15px;">
            @Html.Label("Adresse", htmlAttributes: new { @class = "control-label col-md-4", style = "color: #2196F3; font-weight: bold;" })
            <div class="col-md-10">
                @Html.TextBox("Adresse", ViewBag.Adresse as string, new { @class = "form-control", style = "border: 1px solid #ddd; border-radius: 4px; padding: 8px; width: 100%;" })
            </div>
        </div>

        <div class="form-group" style="margin-bottom: 15px;">
            @Html.Label("Ninea", htmlAttributes: new { @class = "control-label col-md-4", style = "color: #2196F3; font-weight: bold;" })
            <div class="col-md-10">
                @Html.TextBox("Ninea", ViewBag.ninea as string, new { @class = "form-control", style = "border: 1px solid #ddd; border-radius: 4px; padding: 8px; width: 100%;" })
            </div>
        </div>

        <div class="form-group" style="margin-bottom: 15px;">
            @Html.Label("Rccm", htmlAttributes: new { @class = "control-label col-md-4", style = "color: #2196F3; font-weight: bold;" })
            <div class="col-md-10">
                @Html.TextBox("Rccm", ViewBag.rccm as string, new { @class = "form-control", style = "border: 1px solid #ddd; border-radius: 4px; padding: 8px; width: 100%;" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Rechercher" class="btn btn-primary" style="background-color: #2196F3; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; transition: background-color 0.3s;" onmouseover="this.style.backgroundColor='#1e88e5'" onmouseout="this.style.backgroundColor='#2196F3'" />
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Gestionnaire.NomUtilisateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AddresseAgence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Lattitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Longitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().NineaGestionnaire)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().RcmGestionnaire)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Gestionnaire.NomUtilisateur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AddresseAgence)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lattitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NineaGestionnaire)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RcmGestionnaire)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdAgence }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdAgence }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdAgence })
        </td>
    </tr>
}

</table>
@Html.PagedListPager(Model, page=> Url.Action("Index", new {page, Adresse=ViewBag.Adresse, Ninea=ViewBag.Ninea, Rccn=ViewBag.Rccn}))